### ISSUE TITLE
BUG It is possible to create several hashes with the same url

### ISSUE THREAD

**Issue by Michael-Liendo** [whizzes/linx#3]
I think that if the same url already exists on the server, it should deliver the hash created previously.

**Comment by EstebanBorai** [comment]
> I think that if the same url already exists on the server, it should deliver the hash created previously.

Hi @Michael-Liendo,

The reason we don't reuse hashes its because each hash will hold its own metrics in the future. Keeping hashes unique allow us to track usage for each hash independently.

Also keep in mind that links may have a expire time. So we cant actually reuse links/hashes based on the URL they point to in such scenario.

In the future we plan to provide link ownership features, this will allow a user to reactivate or extend link lifetimes and also update them or check metrics about these links.

**Comment by EstebanBorai** [comment]
Im changing the name of this issue due to the fact that this is actually a feature request.

**Comment by Michael-Liendo** [comment]
I see, thanks

**Comment by EstebanBorai** [comment]
Thanks for participating @Michael-Liendo!
